"""
Optimizations
=============
.. autosummary::
:toctree: ../stubs/

Collect1qRuns
Collect2qBlocks
CollectAndCollapse
CollectCliffords
CollectLinearFunctions
CollectMultiQBlocks
CommutationAnalysis
CommutativeCancellation
CommutativeInverseCancellation
ConsolidateBlocks
ContractIdleWiresInControlFlow
ElidePermutations
HoareOptimizer
InverseCancellation
LitinskiTransformation
Optimize1qGates
Optimize1qGatesDecomposition
Optimize1qGatesSimpleCommutation
OptimizeAnnotated
OptimizeCliffordT
OptimizeCliffords
OptimizeSwapBeforeMeasure
RemoveDiagonalGatesBeforeMeasure
RemoveFinalReset
RemoveIdentityEquivalent
RemoveResetInZeroState
ResetAfterMeasureSimplification
Split2QUnitaries
TemplateOptimization
"""

import qiskit.transpiler.passes as qiskit_passes

OPT_PASS_NAMES = """
Collect1qRuns
Collect2qBlocks
CollectAndCollapse
CollectCliffords
CollectLinearFunctions
CollectMultiQBlocks
CommutationAnalysis
CommutativeCancellation
CommutativeInverseCancellation
ConsolidateBlocks
ContractIdleWiresInControlFlow
ElidePermutations
HoareOptimizer
InverseCancellation
LitinskiTransformation
Optimize1qGates
Optimize1qGatesDecomposition
Optimize1qGatesSimpleCommutation
OptimizeAnnotated
OptimizeCliffordT
OptimizeCliffords
OptimizeSwapBeforeMeasure
RemoveDiagonalGatesBeforeMeasure
RemoveFinalReset
RemoveIdentityEquivalent
RemoveResetInZeroState
ResetAfterMeasureSimplification
Split2QUnitaries
TemplateOptimization
""".strip().splitlines()

print(OPT_PASS_NAMES)

from qiskit.transpiler.passes import CommutativeCancellation
